DROP TABLE IF EXISTS `amulet`;
CREATE TABLE IF NOT EXISTS `amulet` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(30) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=44 ;

DROP TABLE IF EXISTS `armour`;
CREATE TABLE IF NOT EXISTS `armour` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(30) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=41 ;

DROP TABLE IF EXISTS `axe`;
CREATE TABLE IF NOT EXISTS `axe` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(30) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=91 ;

DROP TABLE IF EXISTS `bank`;
CREATE TABLE IF NOT EXISTS `bank` (
  `id` int(5) NOT NULL auto_increment,
  `number` varchar(10) default NULL,
  `login` varchar(30) NOT NULL default 'none',
  `password` varchar(30) default NULL,
  `money` varchar(30) NOT NULL default '0',
  `emoney` varchar(30) default '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=36 ;

DROP TABLE IF EXISTS `battles`;
CREATE TABLE IF NOT EXISTS `battles` (
  `id` int(4) NOT NULL auto_increment,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `type` varchar(30) NOT NULL default '',
  `win` varchar(30) NOT NULL default '',
  `status` varchar(30) NOT NULL default '',
  `creator_id` varchar(30) NOT NULL default '',
  `done` varchar(30) NOT NULL default '',
  `hit` varchar(30) NOT NULL default '',
  `turn` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`),
  KEY `id_2` (`id`),
  KEY `id_3` (`id`),
  KEY `id_4` (`id`),
  KEY `id_5` (`id`),
  KEY `id_6` (`id`),
  KEY `id_7` (`id`),
  KEY `id_8` (`id`),
  KEY `id_9` (`id`),
  KEY `id_10` (`id`),
  KEY `id_11` (`id`),
  KEY `id_12` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=316 ;

DROP TABLE IF EXISTS `boardlist`;
CREATE TABLE IF NOT EXISTS `boardlist` (
  `id` bigint(20) NOT NULL auto_increment,
  `name` varchar(50) NOT NULL default '',
  `disc` longtext NOT NULL,
  `date` varchar(30) NOT NULL default '',
  `last_reply` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`),
  KEY `id_3` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=17 ;

DROP TABLE IF EXISTS `book`;
CREATE TABLE IF NOT EXISTS `book` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_water` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `pages` varchar(30) NOT NULL default '',
  `desc` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=16 ;

DROP TABLE IF EXISTS `book_page`;
CREATE TABLE IF NOT EXISTS `book_page` (
  `id` bigint(20) NOT NULL auto_increment,
  `book_id` varchar(30) NOT NULL default '',
  `owner` varchar(30) NOT NULL default '',
  `spell` varchar(30) NOT NULL default '',
  `valid` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `boots`;
CREATE TABLE IF NOT EXISTS `boots` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=9 ;

DROP TABLE IF EXISTS `bot_temp`;
CREATE TABLE IF NOT EXISTS `bot_temp` (
  `id` bigint(20) NOT NULL auto_increment,
  `bot_name` varchar(30) NOT NULL default '',
  `hp` varchar(30) NOT NULL default '',
  `hp_all` varchar(30) NOT NULL default '',
  `battle_id` varchar(30) NOT NULL default '',
  `prototype` varchar(30) NOT NULL default '',
  `team` varchar(30) NOT NULL default '',
  `mana` varchar(30) NOT NULL default '',
  `mana_all` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`),
  KEY `id_3` (`id`),
  KEY `id_4` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=143 ;

DROP TABLE IF EXISTS `clan`;
CREATE TABLE IF NOT EXISTS `clan` (
  `id` bigint(30) NOT NULL auto_increment,
  `name` varchar(30) NOT NULL default '',
  `name_short` varchar(30) NOT NULL default '',
  `glava` varchar(30) NOT NULL default '',
  `site` varchar(30) NOT NULL default '',
  `story` longtext NOT NULL,
  `orden` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=19 ;

DROP TABLE IF EXISTS `clan_zayavka`;
CREATE TABLE IF NOT EXISTS `clan_zayavka` (
  `name` varchar(30) NOT NULL default '',
  `name_short` varchar(5) NOT NULL default '',
  `site` varchar(50) NOT NULL default '',
  `znak` varchar(30) NOT NULL default '',
  `history` mediumtext NOT NULL,
  `orden` varchar(30) NOT NULL default '',
  `glava` varchar(30) NOT NULL default '',
  `glava_fio` varchar(30) NOT NULL default '',
  `sovet1` varchar(30) NOT NULL default '',
  `sovet1_fio` varchar(30) NOT NULL default '',
  `sovet2` varchar(30) NOT NULL default '',
  `sovet2_fio` varchar(30) NOT NULL default '',
  `date` varchar(30) NOT NULL default '',
  `confirm` varchar(30) NOT NULL default ''
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

DROP TABLE IF EXISTS `fail`;
CREATE TABLE IF NOT EXISTS `fail` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(15) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=78 ;

DROP TABLE IF EXISTS `flower`;
CREATE TABLE IF NOT EXISTS `flower` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `mf_krit` varchar(30) default NULL,
  `mf_uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `mf_antikrit` varchar(30) default NULL,
  `mf_antiuvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) NOT NULL default '',
  `orden` varchar(30) NOT NULL default '',
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `gift`;
CREATE TABLE IF NOT EXISTS `gift` (
  `id` bigint(20) NOT NULL auto_increment,
  `name` varchar(30) NOT NULL default '',
  `img` varchar(30) NOT NULL default '',
  `price` varchar(30) NOT NULL default '',
  `wish` varchar(255) NOT NULL default '',
  `mass` varchar(30) NOT NULL default '',
  `type` varchar(30) NOT NULL default '',
  `is_random` varchar(30) NOT NULL default '',
  `g_type` varchar(30) NOT NULL default '',
  `g_id` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `goers`;
CREATE TABLE IF NOT EXISTS `goers` (
  `id` bigint(30) NOT NULL auto_increment,
  `login` varchar(30) NOT NULL default '',
  `time` varchar(30) NOT NULL default '',
  `destenation` varchar(30) NOT NULL default '',
  `dest_game` varchar(30) NOT NULL default '',
  `len` varchar(30) NOT NULL default '',
  `len_done` varchar(30) NOT NULL default '',
  `napr` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=27 ;

DROP TABLE IF EXISTS `helmet`;
CREATE TABLE IF NOT EXISTS `helmet` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=17 ;

DROP TABLE IF EXISTS `hit_session`;
CREATE TABLE IF NOT EXISTS `hit_session` (
  `bid` varchar(30) NOT NULL default '',
  `player1` varchar(50) NOT NULL default '',
  `player2` varchar(50) NOT NULL default '',
  `hit_type` varchar(30) NOT NULL default '',
  `def_type` varchar(30) NOT NULL default '',
  `hit_zone` varchar(30) NOT NULL default '',
  `def_zone` varchar(30) NOT NULL default ''
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;


DROP TABLE IF EXISTS `hit_temp`;
CREATE TABLE IF NOT EXISTS `hit_temp` (
  `attack` varchar(30) default '0',
  `defend` varchar(30) default '0',
  `def_hit1` varchar(30) default '0',
  `def_hit2` varchar(30) default '0',
  `def_block1` varchar(30) default '0',
  `def_block2` varchar(30) default '0'
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

DROP TABLE IF EXISTS `inv`;
CREATE TABLE IF NOT EXISTS `inv` (
  `id` int(4) NOT NULL auto_increment,
  `owner` varchar(30) default NULL,
  `object_id` varchar(30) default NULL,
  `object_type` varchar(30) default NULL,
  `object_razdel` varchar(30) default NULL,
  `gift` varchar(30) default NULL,
  `wear` varchar(30) default NULL,
  `iznos` varchar(30) default NULL,
  `gift_author` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `pages_used` varchar(30) NOT NULL default '',
  `book_name` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=106 ;

DROP TABLE IF EXISTS `knife`;
CREATE TABLE IF NOT EXISTS `knife` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=62 ;

DROP TABLE IF EXISTS `medal`;
CREATE TABLE IF NOT EXISTS `medal` (
  `id` bigint(30) NOT NULL auto_increment,
  `name` varchar(30) NOT NULL default '',
  `img` varchar(30) NOT NULL default '',
  `msg` varchar(255) NOT NULL default '',
  `type` varchar(30) NOT NULL default '',
  `price` varchar(30) NOT NULL default '',
  `disc` longtext NOT NULL,
  `add_l` varchar(30) NOT NULL default '',
  `add_u` varchar(30) NOT NULL default '',
  `mass` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=23 ;

DROP TABLE IF EXISTS `merit`;
CREATE TABLE IF NOT EXISTS `merit` (
  `id` int(25) NOT NULL auto_increment,
  `muj` varchar(25) NOT NULL default '',
  `jena` varchar(25) NOT NULL default '',
  `svid1` varchar(25) NOT NULL default '',
  `svid2` varchar(25) NOT NULL default '',
  `templer` varchar(25) NOT NULL default '',
  `log` text NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=68 ;

DROP TABLE IF EXISTS `miners`;
CREATE TABLE IF NOT EXISTS `miners` (
  `login` varchar(30) NOT NULL default '',
  `time` varchar(30) NOT NULL default '',
  `resource` varchar(30) NOT NULL default '',
  KEY `login` (`login`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

DROP TABLE IF EXISTS `msg`;
CREATE TABLE IF NOT EXISTS `msg` (
  `id` bigint(20) NOT NULL auto_increment,
  `sender` varchar(50) NOT NULL default '',
  `msg` text NOT NULL,
  `parent_board` varchar(30) NOT NULL default '',
  `parent_thread` varchar(30) NOT NULL default '',
  `date` varchar(30) NOT NULL default '',
  `ip` varchar(30) NOT NULL default '',
  `datestamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `orden` varchar(30) NOT NULL default '',
  `level` varchar(30) NOT NULL default '',
  `clan_s` varchar(30) NOT NULL default '',
  `clan` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `obrazy`;
CREATE TABLE IF NOT EXISTS `obrazy` (
  `id` varchar(30) default '0',
  `img` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default ''
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

INSERT DELAYED IGNORE INTO `obrazy` (`id`, `img`, `sex`) VALUES ('1', 'm/10.gif', 'male'),
('2', 'm/11.gif', 'male'),
('3', 'm/12.gif', 'male'),
('4', 'f/10.gif', 'female'),
('5', 'f/11.gif', 'female'),
('6', 'f/12.gif', 'female');

DROP TABLE IF EXISTS `online`;
CREATE TABLE IF NOT EXISTS `online` (
  `id` bigint(15) NOT NULL auto_increment,
  `login` varchar(30) NOT NULL default '',
  `login_display` varchar(30) NOT NULL default '',
  `last_time` varchar(30) NOT NULL default '',
  `uniqPCID` varchar(115) NOT NULL default '',
  `room` varchar(50) NOT NULL default '',
  `city` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=2336 ;

INSERT DELAYED IGNORE INTO `online` (`id`, `login`, `login_display`, `last_time`, `uniqPCID`, `room`, `city`) VALUES (2335, 'X-ray', 'X-ray', '1152468270', '0f456554198ef10f9215874f55b9dffd', 'Банк', 'Моунтаун'),
(2332, 'Loser', 'Loser', '1153991341', '0f456554198ef10f9215874f55b9dffd', 'пл.Базарная', 'Моунтаун');

DROP TABLE IF EXISTS `perchi`;
CREATE TABLE IF NOT EXISTS `perchi` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=12 ;

DROP TABLE IF EXISTS `perevod`;
CREATE TABLE IF NOT EXISTS `perevod` (
  `date` varchar(30) default NULL,
  `login` varchar(30) NOT NULL default '',
  `action` varchar(30) NOT NULL default '',
  `item` varchar(30) NOT NULL default '',
  `ip` varchar(30) NOT NULL default '',
  `time` varchar(30) NOT NULL default '',
  `login2` varchar(30) NOT NULL default '',
  KEY `date` (`date`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

INSERT DELAYED IGNORE INTO `perevod` (`date`, `login`, `action`, `item`, `ip`, `time`, `login2`) VALUES ('10.07.2006', 'X-ray', 'купил', 'Тренеровочный меч (1.00 зл)', '127.0.0.1', '00:36:42', 'оружейная лавка'),
('10.07.2006', 'X-ray', 'выбросил', 'Тренеровочный меч', '127.0.0.1', '00:40:35', 'свалка');

DROP TABLE IF EXISTS `poyas`;
CREATE TABLE IF NOT EXISTS `poyas` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=13 ;

DROP TABLE IF EXISTS `report`;
CREATE TABLE IF NOT EXISTS `report` (
  `id` bigint(15) NOT NULL auto_increment,
  `date` varchar(30) NOT NULL default '',
  `time_stamp` varchar(14) default NULL,
  `login` varchar(30) NOT NULL default '',
  `action` varchar(250) NOT NULL default '',
  `type` varchar(10) NOT NULL default '',
  `ip` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=257 ;

INSERT DELAYED IGNORE INTO `report` (`id`, `date`, `time_stamp`, `login`, `action`, `type`, `ip`) VALUES (220, '25.07.2006-08:02:28', '1153778548', 'X-ray', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(221, '25.07.2006-08:02:40', '1153778560', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(222, '25.07.2006-08:35:30', '1153780530', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(223, '25.07.2006-15:39:55', '1153805995', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(224, '25.07.2006-15:42:18', '1153806138', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(225, '25.07.2006-15:46:54', '1153806414', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(226, '25.07.2006-15:48:25', '1153806505', '12345', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(227, '25.07.2006-15:48:33', '1153806513', '12345', 'Персонаж авторизировался', '1', '127.0.0.1'),
(228, '25.07.2006-17:55:43', '1153814143', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(229, '25.07.2006-17:59:45', '1153814385', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(230, '25.07.2006-18:15:09', '1153815309', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(231, '25.07.2006-18:57:52', '1153817873', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(232, '25.07.2006-19:42:09', '1153820529', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(233, '25.07.2006-20:18:07', '1153822687', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(234, '25.07.2006-20:47:00', '1153824421', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(235, '25.07.2006-21:04:04', '1153825444', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(236, '26.07.2006-19:02:00', '1153904521', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(237, '26.07.2006-20:44:53', '1153910693', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(238, '27.07.2006-17:46:52', '1153986412', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(239, '27.07.2006-18:02:02', '1153987322', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(240, '27.07.2006-18:09:03', '1153987743', '1234567', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(241, '27.07.2006-18:32:21', '1153989141', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(242, '27.07.2006-18:39:52', '1153989592', 'doc_master', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(243, '27.07.2006-18:42:32', '1153989752', 'Loser', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(244, '27.07.2006-18:43:24', '1153989804', 'LoserX', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(245, '27.07.2006-18:44:23', '1153989863', 'Xaker', 'Персонаж зарегистрировался', '0', '127.0.0.1'),
(246, '27.07.2006-19:08:59', '1153991339', 'Loser', 'Персонаж авторизировался', '1', '127.0.0.1'),
(247, '08.07.2006-02:22:46', '1152289366', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(248, '09.07.2006-00:50:16', '1152370216', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(249, '09.07.2006-04:48:30', '1152384510', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(250, '09.07.2006-04:55:59', '1152384959', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(251, '09.07.2006-05:00:17', '1152385217', '12345', 'Персонаж авторизировался', '1', '127.0.0.1'),
(252, '09.07.2006-19:48:12', '1152438493', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(253, '09.07.2006-19:49:52', '1152438592', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(254, '09.07.2006-23:25:30', '1152451530', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(255, '09.07.2006-23:35:02', '1152452102', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1'),
(256, '10.07.2006-04:04:02', '1152468242', 'X-ray', 'Персонаж авторизировался', '1', '127.0.0.1');

DROP TABLE IF EXISTS `ring`;
CREATE TABLE IF NOT EXISTS `ring` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=10 ;

DROP TABLE IF EXISTS `scroll`;
CREATE TABLE IF NOT EXISTS `scroll` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `pages` varchar(30) NOT NULL default '',
  `desc` text NOT NULL,
  `to_book` varchar(30) default NULL,
  `mana` varchar(30) NOT NULL default '',
  `file` varchar(30) NOT NULL default '',
  `school` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=22 ;

DROP TABLE IF EXISTS `shield`;
CREATE TABLE IF NOT EXISTS `shield` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=28 ;

DROP TABLE IF EXISTS `spear`;
CREATE TABLE IF NOT EXISTS `spear` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(15) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=59 ;

DROP TABLE IF EXISTS `sword`;
CREATE TABLE IF NOT EXISTS `sword` (
  `id` int(4) NOT NULL auto_increment,
  `name` varchar(30) default NULL,
  `img` varchar(30) default NULL,
  `bimg` varchar(50) NOT NULL default '',
  `mass` varchar(30) default NULL,
  `price` varchar(30) default NULL,
  `min_sila` varchar(30) default NULL,
  `min_lovkost` varchar(30) default NULL,
  `min_udacha` varchar(30) default NULL,
  `min_power` varchar(30) default NULL,
  `min_intellekt` varchar(30) default NULL,
  `min_vospriyatie` varchar(30) default NULL,
  `min_level` varchar(30) default NULL,
  `add_sila` varchar(30) default NULL,
  `add_lovkost` varchar(30) default NULL,
  `add_udacha` varchar(30) default NULL,
  `add_hp` varchar(30) default NULL,
  `add_intellekt` varchar(30) default NULL,
  `add_mana` varchar(30) default NULL,
  `protect_head` varchar(30) default NULL,
  `protect_corp` varchar(30) default NULL,
  `protect_poyas` varchar(30) default NULL,
  `protect_legs` varchar(30) default NULL,
  `krit` varchar(30) default NULL,
  `uvorot` varchar(30) default NULL,
  `iznos_min` varchar(30) default NULL,
  `iznos_max` varchar(30) default NULL,
  `min_attack` varchar(30) default NULL,
  `max_attack` varchar(30) default NULL,
  `type` varchar(30) default NULL,
  `akrit` varchar(30) default NULL,
  `auvorot` varchar(30) default NULL,
  `sword_vl` varchar(30) default NULL,
  `axe_vl` varchar(30) default NULL,
  `fail_vl` varchar(30) default NULL,
  `knife_vl` varchar(30) default NULL,
  `spear_vl` varchar(30) default NULL,
  `mountown` varchar(30) default NULL,
  `orden` varchar(30) default NULL,
  `add_speed` varchar(30) NOT NULL default '',
  `add_arm_l` varchar(30) NOT NULL default '',
  `add_arm_m` varchar(30) NOT NULL default '',
  `add_arm_h` varchar(30) NOT NULL default '',
  `add_fire` varchar(30) NOT NULL default '',
  `add_water` varchar(30) NOT NULL default '',
  `add_air` varchar(30) NOT NULL default '',
  `add_earth` varchar(30) NOT NULL default '',
  `add_cast` varchar(30) NOT NULL default '',
  `add_trade` varchar(30) NOT NULL default '',
  `add_cure` varchar(30) NOT NULL default '',
  `add_walk` varchar(30) NOT NULL default '',
  `min_sila2` varchar(30) NOT NULL default '',
  `min_lovkost2` varchar(30) NOT NULL default '',
  `min_udacha2` varchar(30) NOT NULL default '',
  `min_power2` varchar(30) NOT NULL default '',
  `min_intellekt2` varchar(30) NOT NULL default '',
  `min_vospriyatie2` varchar(30) NOT NULL default '',
  `min_level2` varchar(30) NOT NULL default '',
  `add_velocity` varchar(30) NOT NULL default '',
  `bron_arm` varchar(30) NOT NULL default '',
  `sex` varchar(30) NOT NULL default '',
  `shot_vl` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=78 ;

INSERT DELAYED IGNORE INTO `sword` (`id`, `name`, `img`, `bimg`, `mass`, `price`, `min_sila`, `min_lovkost`, `min_udacha`, `min_power`, `min_intellekt`, `min_vospriyatie`, `min_level`, `add_sila`, `add_lovkost`, `add_udacha`, `add_hp`, `add_intellekt`, `add_mana`, `protect_head`, `protect_corp`, `protect_poyas`, `protect_legs`, `krit`, `uvorot`, `iznos_min`, `iznos_max`, `min_attack`, `max_attack`, `type`, `akrit`, `auvorot`, `sword_vl`, `axe_vl`, `fail_vl`, `knife_vl`, `spear_vl`, `mountown`, `orden`, `add_speed`, `add_arm_l`, `add_arm_m`, `add_arm_h`, `add_fire`, `add_water`, `add_air`, `add_earth`, `add_cast`, `add_trade`, `add_cure`, `add_walk`, `min_sila2`, `min_lovkost2`, `min_udacha2`, `min_power2`, `min_intellekt2`, `min_vospriyatie2`, `min_level2`, `add_velocity`, `bron_arm`, `sex`, `shot_vl`, `oglushenie`, `aoglushenie`, `osleplenie`, `aosleplenie`, `popadanie`, `promah`) VALUES (1, 'Тренеровочный меч', 'img/sword/new/tmj.gif', 'img/sword/new/tmj.gif', '1', '1', '5', '5', '5', '1', '1', '0', '0', '2', '1', '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', NULL, '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '11', '1');

DROP TABLE IF EXISTS `team1`;
CREATE TABLE IF NOT EXISTS `team1` (
  `player` varchar(30) NOT NULL default '',
  `ip` varchar(30) NOT NULL default '',
  `battle_id` varchar(30) NOT NULL default '',
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `hitted` varchar(30) NOT NULL default '',
  `over` varchar(5) NOT NULL default '',
  KEY `player` (`player`),
  KEY `player_2` (`player`),
  KEY `player_3` (`player`),
  KEY `player_4` (`player`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

DROP TABLE IF EXISTS `team1_history`;
CREATE TABLE IF NOT EXISTS `team1_history` (
  `id` bigint(20) NOT NULL auto_increment,
  `player` varchar(30) NOT NULL default '',
  `ip` varchar(30) NOT NULL default '',
  `hitted` varchar(30) NOT NULL default '',
  `battle_id` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`),
  KEY `id_3` (`id`),
  KEY `id_4` (`id`),
  KEY `id_5` (`id`),
  KEY `id_6` (`id`),
  KEY `id_7` (`id`),
  KEY `id_8` (`id`),
  KEY `id_9` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=152 ;

DROP TABLE IF EXISTS `team2`;
CREATE TABLE IF NOT EXISTS `team2` (
  `player` varchar(30) default NULL,
  `ip` varchar(30) NOT NULL default '',
  `battle_id` varchar(30) NOT NULL default '',
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `hitted` varchar(30) NOT NULL default '',
  `over` varchar(5) NOT NULL default '',
  KEY `player` (`player`),
  KEY `player_2` (`player`),
  KEY `player_3` (`player`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

DROP TABLE IF EXISTS `team2_history`;
CREATE TABLE IF NOT EXISTS `team2_history` (
  `id` bigint(20) NOT NULL auto_increment,
  `player` varchar(30) NOT NULL default '',
  `ip` varchar(30) NOT NULL default '',
  `hitted` varchar(30) NOT NULL default '',
  `battle_id` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`),
  KEY `id_3` (`id`),
  KEY `id_4` (`id`),
  KEY `id_5` (`id`),
  KEY `id_6` (`id`),
  KEY `id_7` (`id`),
  KEY `id_8` (`id`),
  KEY `id_9` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=144 ;

DROP TABLE IF EXISTS `threadlist`;
CREATE TABLE IF NOT EXISTS `threadlist` (
  `id` bigint(20) NOT NULL auto_increment,
  `name` varchar(128) NOT NULL default '',
  `parent_board` varchar(30) NOT NULL default '',
  `sender` varchar(50) NOT NULL default '',
  `date` varchar(30) NOT NULL default '',
  `is_offtop` char(1) NOT NULL default '',
  `last_reply` varchar(30) NOT NULL default '',
  `hits` varchar(30) NOT NULL default '',
  KEY `id` (`id`),
  KEY `id_2` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=160 ;

DROP TABLE IF EXISTS `timeout`;
CREATE TABLE IF NOT EXISTS `timeout` (
  `battle_id` varchar(30) NOT NULL default '',
  `lasthit` varchar(30) NOT NULL default ''
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(4) NOT NULL auto_increment,
  `login` varchar(30) default NULL,
  `login_display` varchar(30) NOT NULL default '',
  `name` varchar(30) default '&#1085;&#1077; &#1091;&#1082;&',
  `password` varchar(30) default NULL,
  `mail` varchar(30) default NULL,
  `sex` varchar(30) default NULL,
  `birthday` varchar(30) default NULL,
  `homepage` varchar(50) NOT NULL default '',
  `town` varchar(30) default '&#1085;&#1077; &#1091;&#1082;&',
  `deviz` varchar(255) default '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;',
  `date` varchar(30) default NULL,
  `hp` varchar(30) default '35',
  `sila` varchar(30) default '5',
  `lovkost` varchar(30) default '5',
  `udacha` varchar(30) default '5',
  `power` varchar(30) default '5',
  `lose` varchar(30) default NULL,
  `win` varchar(30) default NULL,
  `exp` varchar(30) default NULL,
  `amulet` varchar(30) default NULL,
  `hand_r` varchar(30) default NULL,
  `hand_l` varchar(30) NOT NULL default '',
  `hand_l_type` varchar(30) NOT NULL default 'phisic',
  `hobie` longtext,
  `armour` varchar(30) default NULL,
  `poyas` varchar(30) default NULL,
  `obraz` varchar(30) default NULL,
  `vyb_obr` char(2) default '0',
  `ring1` varchar(30) default NULL,
  `ring2` varchar(30) default NULL,
  `ring3` varchar(30) default NULL,
  `helmet` varchar(30) default NULL,
  `perchi` varchar(30) default NULL,
  `shield` varchar(30) default NULL,
  `boots` varchar(30) default NULL,
  `glava` varchar(30) default NULL,
  `money` varchar(30) default NULL,
  `chin` varchar(30) default NULL,
  `bron_head` varchar(30) default NULL,
  `bron_arm` varchar(30) NOT NULL default '',
  `bron_poyas` varchar(30) default NULL,
  `room` varchar(30) default NULL,
  `status` varchar(30) default NULL,
  `ups` varchar(30) default '3',
  `shut` varchar(30) default NULL,
  `prision` varchar(30) default NULL,
  `prision_reason` varchar(255) default NULL,
  `blok` varchar(30) default NULL,
  `blok_reason` varchar(255) default NULL,
  `icq` varchar(30) default NULL,
  `city` varchar(30) default NULL,
  `city_game` varchar(30) default NULL,
  `level` varchar(30) default NULL,
  `intellekt` varchar(30) default '1',
  `vospriyatie` varchar(30) default '1',
  `mana` varchar(30) default '6',
  `mana_all` varchar(30) default '6',
  `hp_all` varchar(30) default '35',
  `phisic_vl` varchar(30) default '1',
  `sword_vl` varchar(30) default '1',
  `axe_vl` varchar(30) default '1',
  `hummer_vl` varchar(30) default '1',
  `castet_vl` varchar(30) default '1',
  `copie_vl` varchar(30) default '1',
  `shot_vl` varchar(30) NOT NULL default '1',
  `sword_bt` varchar(30) default '0',
  `axe_bt` varchar(30) default '0',
  `hummer_bt` varchar(30) default '0',
  `castet_bt` varchar(30) default '0',
  `copie_bt` varchar(30) default '0',
  `shot_bt` varchar(30) default '0',
  `phisic_bt` varchar(30) default '0',
  `next_up` varchar(30) default '30',
  `battle` varchar(30) default NULL,
  `cost` varchar(30) default NULL,
  `travm` varchar(30) default NULL,
  `travm_stat` varchar(30) default NULL,
  `travm_var` varchar(30) default NULL,
  `travm_old_stat` varchar(30) default NULL,
  `hand_r_type` varchar(30) default 'phisic',
  `clan` varchar(30) default NULL,
  `cure_hp` varchar(30) default NULL,
  `movable` varchar(30) default '1',
  `color` varchar(30) default 'black',
  `reg_ip` varchar(30) NOT NULL default '',
  `battle_pos` varchar(30) default NULL,
  `battle_team` varchar(30) default NULL,
  `battle_opponent` varchar(30) NOT NULL default '',
  `orden` varchar(30) default NULL,
  `clan_short` varchar(30) NOT NULL default '',
  `admin_level` varchar(30) NOT NULL default '',
  `clan_take` varchar(30) NOT NULL default '',
  `umenie` varchar(30) NOT NULL default '',
  `cure_mn` varchar(30) NOT NULL default '',
  `water_magic` varchar(30) NOT NULL default '',
  `earth_magic` varchar(30) NOT NULL default '',
  `fire_magic` varchar(30) NOT NULL default '',
  `air_magic` varchar(30) NOT NULL default '',
  `cast` varchar(30) NOT NULL default '',
  `no_armour` varchar(30) NOT NULL default '',
  `light_armour` varchar(30) NOT NULL default '',
  `heavy_armour` varchar(30) NOT NULL default '',
  `trade` varchar(30) NOT NULL default '',
  `cure` varchar(30) NOT NULL default '',
  `walk` varchar(30) NOT NULL default '',
  `mass` varchar(30) NOT NULL default '',
  `otdel` varchar(30) NOT NULL default '',
  `metka` varchar(30) NOT NULL default '',
  `profession` varchar(30) NOT NULL default '',
  `speed` varchar(30) NOT NULL default '5',
  `hand_r_free` varchar(30) NOT NULL default '1',
  `hand_l_free` varchar(30) NOT NULL default '1',
  `hand_r_krit` varchar(30) NOT NULL default '',
  `hand_l_krit` varchar(30) NOT NULL default '',
  `hand_r_antikrit` varchar(30) NOT NULL default '',
  `hand_l_antikrit` varchar(30) NOT NULL default '',
  `hand_r_uvorot` varchar(30) NOT NULL default '',
  `hand_l_uvorot` varchar(30) NOT NULL default '',
  `hand_r_antiuvorot` varchar(30) NOT NULL default '',
  `hand_l_antiuvorot` varchar(30) NOT NULL default '',
  `hand_r_hitmin` varchar(30) NOT NULL default '',
  `hand_l_hitmin` varchar(30) NOT NULL default '',
  `hand_r_hitmax` varchar(30) NOT NULL default '',
  `hand_l_hitmax` varchar(30) NOT NULL default '',
  `zayavka` varchar(30) NOT NULL default '',
  `acsess1` varchar(30) NOT NULL default '',
  `acsess2` varchar(30) NOT NULL default '',
  `animal` varchar(30) NOT NULL default '',
  `state` varchar(30) NOT NULL default '',
  `maxmass` varchar(30) NOT NULL default '30',
  `navik_wood` varchar(30) NOT NULL default '',
  `parent_temp` varchar(30) NOT NULL default '',
  `cure_time` varchar(30) NOT NULL default '1200',
  `adminsite` varchar(25) NOT NULL default '',
  `krit` varchar(30) NOT NULL default '',
  `akrit` varchar(30) NOT NULL default '',
  `uvorot` varchar(30) NOT NULL default '',
  `auvorot` varchar(30) NOT NULL default '',
  `popadanie` varchar(30) NOT NULL default '',
  `promah` varchar(30) NOT NULL default '',
  `oglushenie` varchar(30) NOT NULL default '',
  `aoglushenie` varchar(30) NOT NULL default '',
  `osleplenie` varchar(30) NOT NULL default '',
  `aosleplenie` varchar(30) NOT NULL default '',
  `is_oslep` varchar(30) NOT NULL default '',
  `turn` varchar(30) NOT NULL default '',
  `bron_corp` varchar(30) NOT NULL default '',
  `bron_legs` varchar(30) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=42 ;

INSERT DELAYED IGNORE INTO `users` (`id`, `login`, `login_display`, `name`, `password`, `mail`, `sex`, `birthday`, `homepage`, `town`, `deviz`, `date`, `hp`, `sila`, `lovkost`, `udacha`, `power`, `lose`, `win`, `exp`, `amulet`, `hand_r`, `hand_l`, `hand_l_type`, `hobie`, `armour`, `poyas`, `obraz`, `vyb_obr`, `ring1`, `ring2`, `ring3`, `helmet`, `perchi`, `shield`, `boots`, `glava`, `money`, `chin`, `bron_head`, `bron_arm`, `bron_poyas`, `room`, `status`, `ups`, `shut`, `prision`, `prision_reason`, `blok`, `blok_reason`, `icq`, `city`, `city_game`, `level`, `intellekt`, `vospriyatie`, `mana`, `mana_all`, `hp_all`, `phisic_vl`, `sword_vl`, `axe_vl`, `hummer_vl`, `castet_vl`, `copie_vl`, `shot_vl`, `sword_bt`, `axe_bt`, `hummer_bt`, `castet_bt`, `copie_bt`, `shot_bt`, `phisic_bt`, `next_up`, `battle`, `cost`, `travm`, `travm_stat`, `travm_var`, `travm_old_stat`, `hand_r_type`, `clan`, `cure_hp`, `movable`, `color`, `reg_ip`, `battle_pos`, `battle_team`, `battle_opponent`, `orden`, `clan_short`, `admin_level`, `clan_take`, `umenie`, `cure_mn`, `water_magic`, `earth_magic`, `fire_magic`, `air_magic`, `cast`, `no_armour`, `light_armour`, `heavy_armour`, `trade`, `cure`, `walk`, `mass`, `otdel`, `metka`, `profession`, `speed`, `hand_r_free`, `hand_l_free`, `hand_r_krit`, `hand_l_krit`, `hand_r_antikrit`, `hand_l_antikrit`, `hand_r_uvorot`, `hand_l_uvorot`, `hand_r_antiuvorot`, `hand_l_antiuvorot`, `hand_r_hitmin`, `hand_l_hitmin`, `hand_r_hitmax`, `hand_l_hitmax`, `zayavka`, `acsess1`, `acsess2`, `animal`, `state`, `maxmass`, `navik_wood`, `parent_temp`, `cure_time`, `adminsite`, `krit`, `akrit`, `uvorot`, `auvorot`, `popadanie`, `promah`, `oglushenie`, `aoglushenie`, `osleplenie`, `aosleplenie`, `is_oslep`, `turn`, `bron_corp`, `bron_legs`) VALUES (35, 'X-ray', 'X-ray', '', 'MTIzNDU=', 'fluder2005@yandex.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '25.07.2006-08:02:28', '35', '6', '6', '6', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/10.gif', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9999', NULL, NULL, '', NULL, 'Банк', 'рекрут', '0', '0', NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, '0', '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '0', '', '', '', '', '', '', '', '', '0.1', '1.01', '', '', '', '', '', '4925', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '0', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(36, '12345', '12345', '', 'MTIzNDU=', 'admin@diwaxx.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '25.07.2006-15:48:25', '35', '5', '5', '5', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/1.gif', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'пл.Муниципальная', 'рекрут', '3', '0', NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, '0', '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.05', '', '', '', '', '', '5', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(37, '1234567', '1234567', '', 'MTIzNDU=', 'admin@diwaxx.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '27.07.2006-18:09:03', '35', '5', '5', '5', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/1.gif', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'пл.Базарная', 'рекрут', '3', NULL, NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, NULL, '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '5', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(38, 'doc_master', 'doc_master', '', 'MTIzNDU=', 'wert@mail.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '27.07.2006-18:39:52', '35', '5', '5', '5', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/1.gif', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'пл.Базарная', 'рекрут', '3', NULL, NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, NULL, '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '5', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(39, 'Loser', 'Loser', '', 'MTIzNDU=', 'qwert@qw.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '27.07.2006-18:42:32', '35', '5', '5', '5', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/1.gif', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'пл.Базарная', 'рекрут', '3', '0', NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, '0', '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '5', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(40, 'LoserX', 'LoserX', '', 'MTIzNDU=', 'qwert@qww.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '27.07.2006-18:43:24', '35', '5', '5', '5', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/1.gif', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'пл.Базарная', 'рекрут', '3', NULL, NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, NULL, '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '5', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(41, 'Xaker', 'Xaker', '', 'MTIzNDU=', '12345@yandex.ru', 'male', '01.01.1985', 'http://', '', '&#1085;&#1077; &#1091;&#1082;&#1072;&#1079;&#1072;&#1085;', '27.07.2006-18:44:23', '35', '5', '5', '5', '5', NULL, NULL, NULL, NULL, NULL, '', 'phisic', '', NULL, NULL, 'm/1.gif', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'пл.Базарная', 'рекрут', '3', NULL, NULL, NULL, NULL, NULL, '', 'Моунтаун', 'mountown', '0', '1', '1', '6', '6', '35', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '30', NULL, NULL, NULL, NULL, NULL, NULL, 'phisic', NULL, NULL, '1', 'black', '127.0.0.1', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '5', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '30', '', '', '1200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');

DROP TABLE IF EXISTS `wood`;
CREATE TABLE IF NOT EXISTS `wood` (
  `id` bigint(30) NOT NULL auto_increment,
  `name` varchar(30) NOT NULL default '',
  `img` varchar(30) NOT NULL default '',
  `price` varchar(30) NOT NULL default '',
  `mass` varchar(30) NOT NULL default '',
  `mountown` varchar(30) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=2 ;

INSERT DELAYED IGNORE INTO `wood` (`id`, `name`, `img`, `price`, `mass`, `mountown`) VALUES (1, '&#1044;&#1091;&#1073;', 'wood/dub.gif', '0.3', '2', '26');

DROP TABLE IF EXISTS `zayavka`;
CREATE TABLE IF NOT EXISTS `zayavka` (
  `id` int(30) NOT NULL auto_increment,
  `status` varchar(30) NOT NULL default '',
  `type` varchar(30) NOT NULL default '',
  `term` varchar(30) NOT NULL default '',
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `timeout` varchar(30) NOT NULL default '',
  `battle` varchar(30) NOT NULL default '',
  `creator` varchar(30) NOT NULL default '',
  `minlev1` varchar(30) NOT NULL default '',
  `maxlev1` varchar(30) NOT NULL default '',
  `minlev2` varchar(30) NOT NULL default '',
  `maxlev2` varchar(30) NOT NULL default '',
  `limit1` varchar(30) NOT NULL default '',
  `limit2` varchar(30) NOT NULL default '',
  `wait` varchar(30) NOT NULL default '',
  `all_z` varchar(30) NOT NULL default '',
  `comment` varchar(225) NOT NULL default '',
  `city` varchar(30) NOT NULL default '',
  `room` varchar(30) NOT NULL default '',
  KEY `player1` (`id`),
  KEY `id` (`id`),
  KEY `id_2` (`id`),
  KEY `id_3` (`id`),
  KEY `id_4` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=274 ;

SET FOREIGN_KEY_CHECKS=1;

COMMIT;
        