<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #6677aa 1px solid" bgcolor='#ffffff'>
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1>Страница не найдена</H1></td></tr><tr>
    <td align='left'><br><table cellpadding=10 cellspacing=0 width=100% height=100%><tr><td valign=middle align=left>
	<table cellpadding=0 cellspacing=0>	
	<tr><td><img src=http://www.ultrex.ru/img/404_ru.gif width=193 height=40 border=0 alt='Ошибка 404'></td></tr>
	<tr height=40><td></td></tr>
	<tr><td class=blackvsmall><b>Невозможно найти страницу</b><br><br>Возможно, эта страница была удалена, переименована, или она временно недоступна.</td></tr>
	<tr height=20><td></td></tr>
	<tr height=1><td bgcolor=#717191></td></tr>
	<tr height=20><td></td></tr>
	<tr><td class=blackvsmall>Вы можете сделать следующее:</td></tr>
	<tr height=10><td></td></tr>
	<tr height=16><td class=blackvsmall><img src=http://www.ultrex.ru/img/ico_5.gif width=7 height=7> Откройте <a href=<? echo $url; ?> class=section><b>стартовую страницу</b></a>, затем найдите там ссылку на нужные данные.</td></tr>	
	<tr height=16><td class=blackvsmall><img src=http://www.ultrex.ru/img/ico_5.gif width=7 height=7> Нажмите кнопку  <a href=javascript:history.back() class=section><b>Назад</b></a>, чтобы использовать другую ссылку. </td></tr>
	<tr height=40><td></td></tr>
</table></table></tr></td>
</table>