<script language="JavaScript" src="http://www.ultrex.ru/js/ajax_ru/bandit.php"></script>
<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #6677aa 1px solid" bgcolor='#ffffff'>
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1>Однорукий бандит</H1></td></tr><tr>
    <td align='center'><table width=95% align=center cellspacing="0" cellpadding="0">
          <td align=center>
            <FIELDSET style='PADDING-RIGHT: 6px; PADDING-LEFT: 6px; FONT-SIZE: 11px; PADDING-BOTTOM: 6px; BORDER: #e2e2e2 1px solid; WIDTH: 100%;'><STRONG><LEGEND align=center><b><a id=block_title>Правила игры</a></b></STRONG></LEGEND><br><a id=res>Выбрав размер ставки и тип валюты, нажмите на кнопку "Играть!". В случае выигрыша, Вы получите Вашу ставку, умноженную на число, соответствующее выпавшей комбинации. Рискните, и фортуна Вам улыбнется!</a></FIELDSET></td><tr valign="top"><td align="right" valign="top"><a href="#" onmouseover=view_rules(); class="section"><small>Правила игры</a> <font color='#000000'>/</font> <a href="#" onmouseover=view_table(); onMouseOut=close_table(); class="section"><small>Таблица выигрышей</a></td></table>

<br><br>
<table border="0" cellpadding="0" cellspacing="1" align="center" bgcolor='#000000' id=table_result style='DISPLAY:'>
<tr><td>
  <table border="0" cellpadding="4" cellspacing="1" valign="center" bgcolor='#eeeeee'>
    <tr><td><img id=img_one src="img/7sm.gif" width="40" height="40" align="absMiddle"><img id=img_two src="img/7sm.gif" width="40" height="40" align="absMiddle"><img id=img_three src="img/7sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;"></span></td></tr></table></td></tr></table>

<table border="0" cellpadding="0" cellspacing="1" align="center" bgcolor='#7aa46e' id=table_prizes style='DISPLAY: none'>
<tr>
    <td bgcolor="#7aa46e" class=whitesmall colspan='2' align='center' height="25">Таблица выигрышей</td></tr>
<tr class=blackvsmall><td>
  <table border="0" cellpadding="4" cellspacing="1" valign="center" bgcolor='#eeeeee'>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/7sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/7sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/7sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x10</span></td></tr>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/6sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/6sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/6sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x9</span></td></tr>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/5sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/5sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/5sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x8</span></td></tr>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/4sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/4sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/4sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x7</span></td></tr>
    <tr><td><img src="http://www.ultrex.ru/img/3sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/3sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/3sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x6</span></td></tr>
  </table>
</td>
<td>
  <table border="0" cellpadding="4" cellspacing="1" bgcolor='#eeeeee'>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/2sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/2sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/2sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x5&nbsp;</span></td></tr>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/1sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/1sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/1sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x4</span></td></tr>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/0sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/0sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/0sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x3</span></td></tr>
    <tr><td style="border-bottom: 1 solid #7aa46e"><img src="http://www.ultrex.ru/img/8sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/0sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/0sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x2</span></td></tr>
    <tr><td><img src="http://www.ultrex.ru/img/8sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/8sm.gif" width="40" height="40" align="absMiddle"><img src="http://www.ultrex.ru/img/0sm.gif" width="40" height="40" align="absMiddle"><span style="font-size:14; font-weight: bold;">&nbsp; - &nbsp;x1</span></td></tr>
  </table>
</td>
</tr>
</table>

<br>
<p align='center'><b>ANY</b> - любой символ.</p>

</tr></td>

  <tr>
    <td align='center'><table cellspacing=0 cellpadding=1 border=0 align='center'>

<form name="form1">

<INPUT type=hidden value=<? echo $id; ?> name=p>
<INPUT type=hidden value=<? echo $url; ?> name=url>

<br><br>
<table width="30%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #7aa46e 1px solid">
<tr bgcolor="#7aa46e" class=whitesmall align="center"> 
    <td height="22" style="border-bottom: 1px solid #7aa46e; border-right: 1px solid #ffffff" nowrap> 
      <div align="center">&nbsp;&nbsp;&nbsp;&nbsp;размер ставки&nbsp;&nbsp;&nbsp;&nbsp;</font></div></td>
    <td style="border-bottom: 1px solid #7aa46e" nowrap> 
      <div align="center">&nbsp;&nbsp;&nbsp;&nbsp;тип валюты&nbsp;&nbsp;&nbsp;&nbsp;</div></td></tr>
 <tr align="center"> 
    <td height="22" style="border-right: 1px solid #7aa46e">

<!-- Ставки -->
<select name="moneys" class="input_text_casino">
<option value="100" style="color:blue">100&nbsp;&nbsp;&nbsp;&nbsp;</option>
<option value="70">70</option>
<option value="50">50</option>
<option value="30">30</option>
<option value="20">20</option>				
<option value="10" style="color:maroon">10</option>
<option value="7">7</option>
<option value="5">5</option>
<option value="3">3</option>
<option value="2">2</option>				
<option value="1" style="color:red">1</option>
<option value="0.7">0.7</option>
<option value="0.5">0.5</option>
<option value="0.3">0.3</option>
<option value="0.2">0.2</option>
<option value="0.1" selected>0.1</option>
</select>
<!-- /Ставки -->
</td>
    <td height="22" nowrap> 
<select name="type" class="input_text_casino">
<option selected value="Z" style="color:green">WMZ
<option value="E" style="color:blue">WME&nbsp;&nbsp;&nbsp;
<option value="R" style="color:red">WMR
<option value="U" style="color:olive">WMU
</select></tr></td></tr></table>
<br><br><p align='center'><img id=button src="/img/button.gif" width="130" height="37" style="cursor:hand" border="0" arrow="hand" onclick="GameRequest();" alt="Играть!"></p></form></table>