<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #6677aa 1px solid" bgcolor='#ffffff'>
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1>Наши партнеры</H1></td></tr><tr>
    <td align='center'>

<table width="100%" align="center" border="0" cellspacing="0" cellpadding="10">
<tr><td class=blackvsmall>

<table width="100%" align="center" border="0" cellspacing="0" cellpadding="6" class=blackvsmall>
  <tr class=blackvsmall>
    <td><p align='left'><b>1.</b> <a href="http://www.ultrex.ru/?p=<? echo $id; ?>" title="Интернет казино" class="section"><strong>Интернет казино на WebMoney и E-gold, выгодная партнерская программа</strong></a></td>
  </tr>
  <tr>
    <td><p align='left'><b>2.</b> <!-- Ссылки партнеров --></p></td>
  </tr>
  <tr>
    <td><p align='left'><b>3.</b> <!-- Ссылки партнеров --></p></td>
  </tr>
  <tr>
    <td><p align='left'><b>4.</b></td>
  </tr>
<tr>
    <td><p align='left' valign='center'><b>5.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td>
  </tr>
<tr>
    <td><p align='left'><b>6.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td>
</tr>
<tr>
    <td><p align='left'><b>7.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td>
  </tr>
<tr>
    <td><p align='left'><b>8.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td>
  </tr>
<tr>
    <td><p align='left'><b>9.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>10.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>11.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>12.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>13.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>14.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>15.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>16.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>

<tr>
    <td><p align='left'><b>17.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td></tr>


<tr>
    <td><p align='left'><b>18.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></tr></td>

<tr>
    <td><p align='left'><b>19.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></td>
  </tr>

<tr>
    <td><p align='left'><b>20.</b> <font color="#ff0000"><strong>Место свободно</strong></font></p></tr></td>

</table></td></tr></tr></td></tr></table>

</td></td></tr></table></td></tr></td></tr></table>