<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER-LEFT: #6677aa 1px solid; BORDER-RIGHT: #6677aa 1px solid; BORDER-TOP: #6677aa 1px solid">
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1>Статистика выигрышей</H1></td></tr><tr>
    <td>
<table cellpadding=4 cellspacing=0 width=100% height=100% style="BORDER: #6677aa 1px solid"><tr><td>
<tr><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-right: 1 solid #ffffff' valign='top'><p>WMID (Логин)</p></td><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-right: 1 solid #ffffff' valign='top'><p>Дата</p></td><td width='20%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa' valign='top'><p>Выигрыш</p></td><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-left: 1 solid #ffffff' valign='top'><p>Название игры</p></td></tr>
<script language="JavaScript" src="http://www.ultrex.ru/js/wins.php?p=<? echo $id; ?>"></script></table></tr></td></table>

<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #6677aa 1px solid">
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1><small>TOP 10 самых крупных выигрышей за <u>30 дней</u> [<font color='green'>WMZ</font>]</small></H1></td></tr><tr>
    <td>
<table cellpadding=4 cellspacing=0 width=100% height=100% style="BORDER: #6677aa 1px solid"><tr><td>
<tr><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-right: 1 solid #ffffff' valign='top'><p>WMID (Логин)</p></td><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-right: 1 solid #ffffff' valign='top'><p>Дата</p></td><td width='20%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa' valign='top'><p>Выигрыш</p></td><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-left: 1 solid #ffffff' valign='top'><p>Название игры</p></td></tr>
<script language="JavaScript" src="http://www.ultrex.ru/js/big_wins_wmz.php?p=<? echo $id; ?>"></script></table></tr></td></table>

<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #6677aa 1px solid">
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1><small>TOP 10 самых крупных выигрышей за <u>30 дней</u> [<font color='#ff0000'>WMR</font>]</small></H1></td></tr><tr>
    <td>
<table cellpadding=4 cellspacing=0 width=100% height=100% style="BORDER: #6677aa 1px solid"><tr><td>
<tr><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-right: 1 solid #ffffff' valign='top'><p>WMID (Логин)</p></td><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-right: 1 solid #ffffff' valign='top'><p>Дата</p></td><td width='20%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa' valign='top'><p>Выигрыш</p></td><td width='25%' class=whitesmall bgcolor="#88aadd" align='center' style='border-bottom: 1 solid #6677aa; border-left: 1 solid #ffffff' valign='top'><p>Название игры</p></td></tr>
<script language="JavaScript" src="http://www.ultrex.ru/js/big_wins_wmr.php?p=<? echo $id; ?>"></script></table></tr></td></table>