<script language="JavaScript" src="http://www.ultrex.ru/js/week_bonus.php"></script>
<table>
<table width="100%" align="center" border="0" cellspacing="0" cellpadding="4" style="BORDER: #6677aa 1px solid" bgcolor='#ffffff'>
<tr><td bgcolor="#88aadd" class=whitesmall align='center' height="25" style="BORDER-BOTTOM: #6677aa 1px solid"><H1>Еженедельный бонус</H1></td></tr><tr>
    <tr>
    <td align='left' class=blackvsmall>
<TR>
    <TD align=left>
      <TABLE height="100%" cellSpacing=0 cellPadding=2 width="100%">       
        <TR><TD><TABLE height="100%" cellSpacing=0 cellPadding=7 width="100%">              
              <TR>
                <TD class=blackvsmall>
                  <P>Если Вы будете на протяжении недели (от понедельника до понедельника) играть в <b>наши</b> лотереи <b>больше других</b>, то мы будем выплачивать Вам по <font color=black><b><font color='#ff0000'>100</font></b></font> <b>WM<font color='#ff0000'>R</font></b> каждый <font color=red><u>понедельник</u></FONT>!<BR><BR><IMG height=7 
                  src="/img/ico_5.gif" width=7> <script language="JavaScript">
<!--
document.write(new_week); 
//-->
</script><BR><BR><IMG 
                  height=7 src="/img/ico_5.gif" width=7> <script language="JavaScript">
<!--
document.write(old_week); 
//-->
</script><BR><BR></FONT></P></TD></TR></TABLE></TD></TR></table>
</td></tr>
</tr></td></table>